//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesMarketPlace.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoteDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NoteDetails()
        {
            this.Downloads = new HashSet<Downloads>();
            this.NoteReview = new HashSet<NoteReview>();
            this.SellerNotesAttachments = new HashSet<SellerNotesAttachments>();
            this.SpamReports = new HashSet<SpamReports>();
        }
    
        public int ID { get; set; }
        public int UID { get; set; }
        public int Status { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string NoteTitle { get; set; }
        public string DisplayPicture { get; set; }
        public string NumberOfPages { get; set; }
        public string Description { get; set; }
        public string University { get; set; }
        public string InstitutionName { get; set; }
        public string Course { get; set; }
        public string CourseCode { get; set; }
        public string Professor { get; set; }
        public bool IsPaid { get; set; }
        public decimal SellPrice { get; set; }
        public string NotesPreview { get; set; }
        public string Action { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual AddCategory AddCategory { get; set; }
        public virtual AddCountry AddCountry { get; set; }
        public virtual AddType AddType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Downloads> Downloads { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoteReview> NoteReview { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellerNotesAttachments> SellerNotesAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpamReports> SpamReports { get; set; }
        public virtual NoteDetails NoteDetails1 { get; set; }
        public virtual NoteDetails NoteDetails2 { get; set; }
        public virtual NoteDetails NoteDetails11 { get; set; }
        public virtual NoteDetails NoteDetails3 { get; set; }
        public virtual ReferenceData ReferenceData { get; set; }
    }
}
